### ISSUE TITLE
Potential bug in gradual oxygen refilling

### ISSUE THREAD

**Issue by AdalynBlack** [SmileHappyMods/BetterOxygen#1]
I was working on making a pull request to make the oxygen refill rate configurable, and I noticed that the way in which oxygen refilling is handled appears to be bugged.
The code uses a while loop, along with a "preventSpeed" variable that runs until preventSpeed is > 1. preventSpeed is incremented by deltaTime, and the remaining oxygen amount is incremented by a constant multiplied by the deltaTime. This effectively means that you are refilling `(CONSTANT * deltaTime) / deltaTime` oxygen per function call, which would boil down to just increasing by the constant factor each time the function gets called. I'm guessing that this behaviour is unintended. If it is intended, then the equation could be simplified to just increase by a constant factor

**Comment by AdalynBlack** [comment]
I have confirmed in-game that it is indeed framerate dependent currently
At my max framerate of ~150 fps, I refill 4x faster than at 30

**Comment by SmileHappyMods** [comment]
Everything here looks great, thank you. Only issue I have found so far is that the limits were removed for refilling oxygen and it goes over max, but I have fixed that myself.
